# Generated by Django 3.2.9 on 2021-11-26 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_movieimages_movieimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
