# Generated by Django 3.2.9 on 2021-11-28 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='problem',
            new_name='movie',
        ),
    ]
